version: '2.1'

services:

  boysoft-authentication-ms:
    build: .
    ports:
      - "4002:4002"
    depends_on: 
      boysoft-authentication-db:
        condition: service_healthy
    links:
      - boysoft-authentication-db
    networks:
      - authNet

  boysoft-authentication-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: authentication
      MYSQL_USER: juanpablo
      MYSQL_PASSWORD: 12345
    ports:
      - "3309:3306"
    networks:
      - authNet
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15

networks:
  authNet:
    driver: bridge